version: '3'
services:
  envoy:
    container_name: envoy
    build: .
    ports:
      - "10000:10000"
      - "9902:9902"
    volumes:
      - ./logs:/logs

  jekyll:
    container_name: jekyll
    image: jekylocal
    command: jekyll serve --watch --drafts --host -H 0.0.0.0
    ports:
      - "4000:4000"
    volumes:
      - /Users/dewet/code/dewetblomerus.github.io:/home/jekyll
